# Generated by Django 2.2.1 on 2019-10-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('parent', models.CharField(max_length=25)),
                ('founded', models.IntegerField()),
                ('focus_category', models.CharField(max_length=25)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('specs', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getMeARetailerApp.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getMeARetailerApp.Provider')),
                ('delivery_time', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getMeARetailerApp.Product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='getMeARetailerApp.Provider')),
            ],
            bases=('getMeARetailerApp.provider',),
        ),
    ]
