# Generated by Django 2.2.1 on 2019-10-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getMeARetailerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistic',
            name='provider',
        ),
    ]
